### ISSUE TITLE
Crystal name 0603 don't match his dimensions

### ISSUE THREAD

**Issue by suzizecat** [KiCad/Crystals.pretty#24]
The `Crystal_SMD_0603-2pin_6.0x3.5mm*` footprint name should be `6035` instead of `0603` (or the dimension should be 0.6x0.3mm but this seems suspicious) 

Should i change that with a PR (in which way ?)

Best,
Julien

**Comment by evanshultz** [comment]
@suzizecat 
Hi Julien. This is interesting. The datasheet mentioned for the 0603 footprint (http://www.petermann-technik.de/fileadmin/petermann/pdf/SMD0603-2.pdf) calls the package"0603", but the dimensions are indeed 6.0x3.5mm. Other crystals use the part dimensions in the footprint name 2012 is http://txccrystal.com/images/pdf/9ht11.pdf). So this is only a problem in that it's inconsistent, since "0603" matches the manufacturer name.

But since this crystal is the outlier in an otherwise-consistent crystal footprint naming scheme, I agree with the change you're proposing. That will align the entire library. @SchrodingersGat @poeschlr 

Here are footprints for 2-pin and 4-pin 6.0x3.5mm crystals that use a "normal" naming scheme:
http://www.ecsxtal.com/store/pdf/ecx-64a_ecx-64cr.pdf
http://www.ecsxtal.com/store/pdf/ecx_64r.pdf

If you can, Julien, please fork the repo and submit a PR for this issue (do all 4 footprints at once). While you're at it, please verify the footprints fit the above crystals and update the datasheets to eliminate future confusion. If you're not able to do that, let me know and I will. Thanks again for reporting this issue!

**Comment by suzizecat** [comment]
I'll do that within few days then.

**Comment by SchrodingersGat** [comment]
@suzizecat I'm closing this issue as this repo is now marked as legacy. Please readdress this issue to https://github.com/kicad/kicad-footprints
